services:
  web:
    container_name: price-comparator
    image: ghcr.io/guillaumeca/price-comparator:${IMAGE_TAG}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pricecomparator.rule=Host(`price-comparator.irong.fr`)"
      - "traefik.http.routers.pricecomparator.entrypoints=websecure"
      - "traefik.http.routers.pricecomparator.tls.certresolver=myresolver"
      - "traefik.docker.network=web"
      - "traefik.http.routers.pricecomparator.middlewares=pricecomparator"
      - "traefik.http.middlewares.pricecomparator.ratelimit.average=30"
      - "traefik.http.middlewares.pricecomparator.ratelimit.burst=50"
    environment:
      AUTH_TRUST_HOST: true
    volumes:
      - ./db:/app/db
    networks:
      - web
    depends_on:
      - migration
    deploy:
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
    mem_limit: 100m

  migration:
    container_name: price-comparator-migration
    image: ghcr.io/guillaumeca/price-comparator/migration:${IMAGE_TAG}
    volumes:
      - ./db:/app/db

networks:
  web:
    external: true
