name: Build and Push

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      image-name:
        required: true
        type: string
      context:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: ${{ inputs.username }}/${{ inputs.image-name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📖 Checkout Code
        uses: actions/checkout@v4

      - name: 🎛️ Set environment
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "${{ secrets.WEB_ENV_FILE }}" > .env
          echo "${{ secrets.WEB_ENV_FILE }}" > .env.production

      - name: 🔐 Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🐳 Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:buildcache,mode=max

      - name: 🧹 Cleanup Old Image Versions
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ inputs.username }}
          package-name: ${{ inputs.image-name }}
          package-type: container
          min-versions-to-keep: 20
